stages:
  stage_load_save:
    cmd: python src/stage_01_load_save.py
    deps: 
      - src/stage_01_load_save.py
      - src/utils/all_utils.py
      - config/config.yaml
    outs:
      - artifacts/raw_local_dir/data.csv
    
  stage_save_data:
    cmd: python src/stage_02_split_data.py
    deps:
      - python src/stage_02_split_data.py
      - config/config.yaml
      - params.yaml
      - src/utils/all_utils.py
    outs:
      - artifacts/split_data_dir/train.csv
      - artifacts/split_data_dir/test.csv
