stages:
  stage_load_save:
    cmd: python src/stage_01_load_save.py --config=config/config.yaml
    deps: 
      - src/stage_01_load_save.py
      - src/utils/all_utils.py
      - config/config.yaml
    outs:
      - artifacts/raw_local_dir/data.csv
    
  stage_save_data:
    cmd: python src/stage_02_split_data.py --config=config/config.yaml --params=params.yaml
    deps:
      - src/stage_02_split_data.py
      - config/config.yaml
      - src/utils/all_utils.py
    params:
      - base.test_size
      - base.random_state
    outs:
      - artifacts/split_data_dir/train.csv
      - artifacts/split_data_dir/test.csv
    
  stage_train_data:
    cmd: python src/stage_03_train_data.py --config=config/config.yaml --params=params.yaml
    deps:
      - src/stage_03_train_data.py
      - config/config.yaml
      - artifacts/split_data_dir/train.csv
      - src/utils/all_utils.py
      - artifacts/split_data_dir/test.csv
    params:
      - model_params.ElasticNet.alpha
      - model_params.ElasticNet.l1_ratio
      - base.random_state
    outs: 
      - artifacts/model_dir/elasticnet_model.txt
